# Generated by Django 4.0.3 on 2022-03-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.TextField()),
                ('Book_Name', models.TextField()),
                ('Group', models.TextField(max_length=30)),
                ('Semester', models.TextField()),
                ('Uploaded_By', models.TextField()),
                ('File', models.FileField(blank=True, null=True, upload_to='User_Media')),
                ('Filesize', models.TextField()),
            ],
        ),
    ]
